document.body.querySelector('#usage-browser-btn')
  ?.addEventListener("click", () => {
    document.body.querySelector('#usage-browser-btn')
      ?.classList.add('!bg-neutral', '!text-neutral-content', 'tab-active')
    document.body.querySelector('#usage-nodejs-btn')
      ?.classList.remove('!bg-neutral', '!text-neutral-content', 'tab-active')
    document.body.querySelector('#usage-browser-content')
      ?.classList.remove('!hidden')
    document.body.querySelector('#usage-nodejs-content')
      ?.classList.add('!hidden')
  })

document.body.querySelector('#usage-nodejs-btn')
  ?.addEventListener("click", () => {
    document.body.querySelector('#usage-browser-btn')
      ?.classList.remove('!bg-neutral', '!text-neutral-content', 'tab-active')
    document.body.querySelector('#usage-nodejs-btn')
      ?.classList.add('!bg-neutral', '!text-neutral-content', 'tab-active')
    document.body.querySelector('#usage-browser-content')
      ?.classList.add('!hidden')
    document.body.querySelector('#usage-nodejs-content')
      ?.classList.remove('!hidden')
  })

document.body.querySelector('#install-browser-btn')
  ?.addEventListener("click", () => {
    document.body.querySelector('#install-browser-btn')
      ?.classList.add('!bg-neutral', '!text-neutral-content', 'tab-active')
    document.body.querySelector('#install-nodejs-btn')
      ?.classList.remove('!bg-neutral', '!text-neutral-content', 'tab-active')
    document.body.querySelector('#install-browser-content')
      ?.classList.remove('!hidden')
    document.body.querySelector('#install-nodejs-content')
      ?.classList.add('!hidden')
  })

document.body.querySelector('#install-nodejs-btn')
  ?.addEventListener("click", () => {
    document.body.querySelector('#install-browser-btn')
      ?.classList.remove('!bg-neutral', '!text-neutral-content', 'tab-active')
    document.body.querySelector('#install-nodejs-btn')
      ?.classList.add('!bg-neutral', '!text-neutral-content', 'tab-active')
    document.body.querySelector('#install-browser-content')
      ?.classList.add('!hidden')
    document.body.querySelector('#install-nodejs-content')
      ?.classList.remove('!hidden')
  })